version: 0.2

phases:
  pre_build:
    runtime-versions:
        nodejs: 8.10
    commands:
    - npm install --no-progress --silent
  build:
    commands:
    - npm run-script lint
    - npm run test
